eth:
  protocol: ws
  host: 127.0.0.1
  port: 8546
db:
  driver: mysql
  host: ws-database
  port: 3306
  name: ethdb
  user: root
  password: my-secret-pw
sync:
  targetBlock: 0
  fromBlock: 0
pprof:
  enable: false
  port: 8000
  address: "0.0.0.0"