eth:
  - protocol: ws
    host: 127.0.0.1
    port: 8546
  - protocol: ws
    host: 127.0.0.1
    port: 8547
db:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  name: ethdb
  user: root
  password: my-secret-pw
sync:
  fromBlock: 0
pprof:
  enable: false
  port: 8000
  address: "0.0.0.0"
functions:
  erc20token: true
chain:
  test: false
